//Game
const GAME_SCALE = 2.5;

//Mario height and width
const SMALL_MARIO_HEIGHT = 16;
const SMALL_MARIO_WIDTH = 16;
const MEDIUM_MARIO_HEIGHT = 20;
const MEDIUM_MARIO_WIDTH = 18;
const LARGE_MARIO_HEIGHT = 24;
const LARGE_MARIO_WIDTH = 20;

//Mario speed
const MARIO_SPEED = 2;

//Gravity
const GRAVITY = 0.5;

//Mario vertical velocity
const SMALL_MARIO_VERTICAL_VELOCITY = 8;
const MEDIUM_MARIO_VERTICAL_VELOCITY = 10;
const LARGE_MARIO_VERTICAL_VELOCITY = 10;
const DEAD_MARIO_VERTICAL_VELOCITY = 2;

//Bullet
const BULLET_HEIGHT = 10;
const BULLET_WIDTH = 10;
const COLLISION_BULLET_HEIGHT = 16;
const COLLISION_BULLET_WIDTH = 16;
const BULLET_SPEED = 3;
const VERTICAL_BULLET_VELOCITY = 4;

//Goomba
const GOOMBA_VERTICAL_VELOCITY = 5;
const GOOMBA_SPEED = 2;

//Koopa
const KOOPA_VERTICAL_VELOCITY = 5;
const KOOPA_SPEED = 0.8;

//Snail
const SNAIL_VERTICAL_VELOCITY = 5;
const SNAIL_SPEED = 1;

//Mushroom
const MUSHROOM_WIDTH = 16;
const MUSHROOM_HEIGHT = 16;
const MUSHROOM_VERTICAL_VELOCITY = 5;
const MUSHROOM_SPEED = 1;

//Coin
const COIN_HEIGHT = 16;
const COIN_WIDTH = 16;

//Flower
const FLOWER_WIDTH = 16;
const FLOWER_HEIGHT = 24;